version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
